edit: main.obj test.obj list.obj mergeSort.obj readFromFile.obj
	cl main.obj test.obj list.obj mergeSort.obj readFromFile.obj

main.obj: main.cpp
	cl -c main.cpp

test.obj: test.cpp
	cl -c test.cpp

list.obj: list.cpp
	cl -c list.cpp

mergeSort.obj: mergeSort.cpp
	cl -c mergeSort.cpp


readFromFile.obj: readFromFile.cpp
	cl -c readFromFile.cpp

clean:
	rm edit main.obj list.obj test.obj mergeSort.obj 